[package]
name = "yavashark_swc_validator"
version = "0.1.0"
edition = "2024"

[dependencies]
swc_common = "19.0.0"
swc_ecma_ast = "21.0.0"
swc_ecma_visit = "21.0.0"
unicode-ident = "1.0.19"

[dev-dependencies]
swc_ecma_parser = "35.0.0"

[lints]
workspace = true
