[package]
name = "yavashark_swc_validator"
version = "0.1.0"
edition = "2024"

[dependencies]
swc_common = "17.0.1"
swc_ecma_ast = "18.0.0"
swc_ecma_visit = "18.0.1"
unicode-ident = "1.0.19"

[dev-dependencies]
swc_ecma_parser = "27.0.4"

[lints]
workspace = true
