[package]
name = "yavashark_codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
yavashark_bytecode = { path = "../yavashark_bytecode" }
swc_ecma_parser = "35.0.0"
swc_ecma_ast = "21.0.0"
swc_common = "19.0.0"
anyhow = "1.0.86"
log = "0.4.22"

[lints]
workspace = true
