[package]
name = "yavashark_codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
yavashark_bytecode = { path = "../yavashark_bytecode" }
swc_ecma_parser = "27.0.4"
swc_ecma_ast = "18.0.0"
swc_common = "17.0.1"
anyhow = "1.0.86"
log = "0.4.22"

[lints]
workspace = true
